/**
 * Delivery-note PDF generation (client-side).
 *
 * Builds a self-contained HTML delivery note from a Delivery and renders it to a
 * PDF on-device via expo-print, then shares it. Mirrors invoicePdf.ts.
 * NOTE: file is named `deliveryNote.ts` (NOT `*.pdf.ts`) — Metro treats `.pdf`
 * as an asset extension and would break the import.
 */
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Delivery } from '@/shared/types/delivery';

export interface DeliveryNoteOptions {
  businessName?: string;
  businessAddress?: string;
  currencySymbol?: string;
}

function esc(value?: string | number | null): string {
  if (value === undefined || value === null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(iso?: string | null): string {
  if (!iso) return '';
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? '' : d.toLocaleString();
}

function buildHtml(delivery: Delivery, opts: DeliveryNoteOptions): string {
  const cur = opts.currencySymbol || '$';
  const rows = (delivery.items || [])
    .map(
      (it) => `
      <tr>
        <td>${esc(it.name)}</td>
        <td class="num">${esc(it.quantityOrdered)}</td>
        <td class="num">${cur}${(Number(it.price) || 0).toFixed(2)}</td>
        <td class="num">${cur}${((Number(it.price) || 0) * (Number(it.quantityOrdered) || 0)).toFixed(2)}</td>
      </tr>`
    )
    .join('');

  return `
  <html><head><meta charset="utf-8" /><style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1C1917; padding: 28px; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .muted { color: #78716C; font-size: 13px; }
    .row { display: flex; justify-content: space-between; margin-top: 18px; }
    .box { font-size: 13px; line-height: 1.5; }
    .label { color: #78716C; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
    table { width: 100%; border-collapse: collapse; margin-top: 22px; font-size: 13px; }
    th { text-align: left; border-bottom: 2px solid #ECE6DF; padding: 8px 6px; color: #57534E; }
    td { border-bottom: 1px solid #F0EDE8; padding: 8px 6px; }
    .num { text-align: right; }
    .total { text-align: right; font-size: 15px; font-weight: 600; margin-top: 14px; }
    .sign { margin-top: 48px; display: flex; justify-content: space-between; }
    .sign div { width: 45%; border-top: 1px solid #1C1917; padding-top: 6px; font-size: 12px; color: #57534E; }
    .footer { margin-top: 40px; color: #A8A29E; font-size: 11px; text-align: center; }
  </style></head><body>
    <h1>Delivery Note</h1>
    <div class="muted">${esc(delivery.id)}</div>
    <div class="row">
      <div class="box">
        <div class="label">From</div>
        ${esc(opts.businessName || delivery.distributorName || '')}<br/>${esc(opts.businessAddress || '')}
      </div>
      <div class="box" style="text-align:right">
        <div class="label">To</div>
        ${esc(delivery.clientCompanyName || '')}<br/>${esc(delivery.clientAddress || '')}
      </div>
    </div>
    <div class="row">
      <div class="box"><div class="label">Expected</div>${esc(formatDate(delivery.expectedDeliveryDateTime))}</div>
      <div class="box" style="text-align:right"><div class="label">Tracking</div>${esc(delivery.trackingNumber || '—')}</div>
    </div>
    <table>
      <thead><tr><th>Item</th><th class="num">Qty</th><th class="num">Unit</th><th class="num">Total</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="4" class="muted">No items</td></tr>'}</tbody>
    </table>
    ${delivery.totalAmount != null ? `<div class="total">Total: ${cur}${Number(delivery.totalAmount).toFixed(2)}</div>` : ''}
    ${delivery.distributorNotes ? `<div class="box" style="margin-top:18px"><div class="label">Notes</div>${esc(delivery.distributorNotes)}</div>` : ''}
    <div class="sign"><div>Received by (name &amp; signature)</div><div>Date</div></div>
    <div class="footer">Generated by NouPro</div>
  </body></html>`;
}

export async function generateDeliveryNotePdf(delivery: Delivery, opts: DeliveryNoteOptions = {}): Promise<string> {
  const html = buildHtml(delivery, opts);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  return uri;
}

/** Generate + open the share sheet for a delivery note. */
export async function shareDeliveryNote(delivery: Delivery, opts: DeliveryNoteOptions = {}): Promise<void> {
  const uri = await generateDeliveryNotePdf(delivery, opts);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Delivery note' });
  }
}
