/**
 * Collection Repository - Prisma Implementation
 *
 * Internal product groupings. A Collection belongs to a business and holds a
 * curated set of that business's products via the CollectionProduct join table
 * (many-to-many). Mirrors brandRepo; the join mirrors PriceListItem.
 */
const { prisma } = require('../../db/prisma');

const productInclude = {
  products: {
    include: { product: true },
    orderBy: { displayOrder: 'asc' },
  },
  _count: { select: { products: true } },
};

async function getByBusinessId(businessId) {
  return prisma.collection.findMany({
    where: { businessId },
    orderBy: { name: 'asc' },
    include: productInclude,
  });
}

async function getById(id) {
  return prisma.collection.findUnique({
    where: { id },
    include: productInclude,
  });
}

async function countByBusinessId(businessId) {
  return prisma.collection.count({ where: { businessId } });
}

async function create(data) {
  return prisma.collection.create({ data });
}

async function update(id, patch) {
  return prisma.collection.update({
    where: { id },
    data: patch,
  });
}

async function remove(id) {
  try {
    await prisma.collection.delete({ where: { id } });
    return true;
  } catch (e) {
    return false;
  }
}

// rows: [{ id, collectionId, productId }] — ids generated by the caller (server.js).
async function addProducts(rows) {
  if (!Array.isArray(rows) || rows.length === 0) return { count: 0 };
  return prisma.collectionProduct.createMany({ data: rows, skipDuplicates: true });
}

async function removeProduct(collectionId, productId) {
  return prisma.collectionProduct.deleteMany({ where: { collectionId, productId } });
}

module.exports = {
  getByBusinessId,
  getById,
  countByBusinessId,
  create,
  update,
  delete: remove,
  addProducts,
  removeProduct,
};
