/**
 * Recipe Repository - Prisma Implementation
 *
 * A Recipe is a bill-of-materials attached to a finished Product: it lists
 * ingredient products with quantities. Mirrors collectionRepo; the ingredient
 * join mirrors CollectionProduct with an added quantity/unit per line.
 */
const { prisma } = require('../../db/prisma');

const recipeInclude = {
  product: { select: { id: true, name: true, price: true, costPrice: true, productPicture: true, unit: true } },
  ingredients: {
    include: { product: { select: { id: true, name: true, costPrice: true, unit: true, productPicture: true } } },
    orderBy: { createdAt: 'asc' },
  },
};

async function getByBusinessId(businessId) {
  return prisma.recipe.findMany({ where: { businessId }, orderBy: { name: 'asc' }, include: recipeInclude });
}

async function getById(id) {
  return prisma.recipe.findUnique({ where: { id }, include: recipeInclude });
}

async function countByBusinessId(businessId) {
  return prisma.recipe.count({ where: { businessId } });
}

async function create(data) {
  return prisma.recipe.create({ data, include: recipeInclude });
}

async function update(id, patch) {
  return prisma.recipe.update({ where: { id }, data: patch, include: recipeInclude });
}

async function remove(id) {
  try {
    await prisma.recipe.delete({ where: { id } });
    return true;
  } catch (e) {
    return false;
  }
}

// rows: [{ id, recipeId, productId, quantity, unit }] — ids generated by the caller.
async function addIngredients(rows) {
  if (!Array.isArray(rows) || rows.length === 0) return { count: 0 };
  return prisma.recipeIngredient.createMany({ data: rows, skipDuplicates: true });
}

async function updateIngredient(id, patch) {
  return prisma.recipeIngredient.update({ where: { id }, data: patch });
}

async function removeIngredient(recipeId, productId) {
  return prisma.recipeIngredient.deleteMany({ where: { recipeId, productId } });
}

module.exports = {
  getByBusinessId,
  getById,
  countByBusinessId,
  create,
  update,
  delete: remove,
  addIngredients,
  updateIngredient,
  removeIngredient,
};
